name: Alias Game Team 1

on:
  push:
    branches:
      - CI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build


      - name: Connect to DB
        run: docker run --name couchDB -p5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin couchdb:3.3.2 -d  
      # - name: Check connection to DB
      #   run: curl http://localhost:5984  

      # - name: Tests
      #   run: npm test
